var sql = `
    USE JWLIBRARY;

    IF(EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG = 'JWLIBRARY' AND TABLE_SCHEMA = 'DBO' AND TABLE_NAME = 'USER'))
    BEGIN
        -- CREATE USER TABLE
        DROP TABLE IF EXISTS [DBO].[USER_BACKUP];

        SELECT *
        INTO [DBO].[USER_BACKUP]
        FROM [DBO].[USER];

        DROP TABLE IF EXISTS [DBO].[USER];

        CREATE TABLE [DBO].[USER]
        (
            ID INT NOT NULL IDENTITY(1,1),
            USERID NVARCHAR(30) NOT NULL,
            TEL_TYPE INT NOT NULL,
            TEL NVARCHAR(20) NOT NULL,
            EMAIL NVARCHAR(40) NOT NULL,
            WRITE_ID NVARCHAR(30) NOT NULL,
            WRITE_DT DATETIME NOT NULL DEFAULT GETDATE(),
            MODIFY_ID NVARCHAR(30) NOT NULL,
            MODIFY_DT DATETIME NOT NULL DEFAULT GETDATE(),
            PRIMARY KEY(ID, USERID)
            -- ADD COLUMNS --
        );

        INSERT INTO [DBO].[USER]
        SELECT USERID, TEL_TYPE, TEL, EMAIL, WRITE_ID, WRITE_DT, MODIFY_ID, MODIFY_DT
        FROM [DBO].[USER_BACKUP];
    END
    ELSE
    BEGIN
        CREATE TABLE [DBO].[USER]
        (
            ID INT NOT NULL IDENTITY(1,1),
            USERID NVARCHAR(30) NOT NULL,
            TEL_TYPE INT NOT NULL,
            TEL NVARCHAR(20) NOT NULL,
            EMAIL NVARCHAR(40) NOT NULL,
            WRITE_ID NVARCHAR(30) NOT NULL,
            WRITE_DT DATETIME NOT NULL DEFAULT GETDATE(),
            MODIFY_ID NVARCHAR(30) NOT NULL,
            MODIFY_DT DATETIME NOT NULL DEFAULT GETDATE(),
            PRIMARY KEY(ID, USERID)
            -- ADD COLUMNS --
        );
    END
`;